sudo: required
dist: trusty
language: python
python:
  - 3.5
  - 3.6

install:
  - pip install -r dev_requirements.txt

script:
  - python setup.py develop
  - python setup.py test
  - python setup.py sdist

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: gJ98IKzZZB9HjkPPO9veNMZH2/gz78eQzUBYFgtt4FkT0QGb+9tYUrTOCgn7vaa1cPuS6Ntc8uAZUOKxxQuqaHTCalPuZhudiQHgllsa56lWcEK8c23byhd3gBXLfd9bKsgAVzZJKRebrhNzEEKw08z/6399Aa0C4iMFb6xfEwA=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
